name: hammock_mapper
version: 0.0.2
author: Victor Savkin <vic.savkin@gmail.com>
homepage: https://github.com/vsavkin/hammock_mapper
dependencies:
  hammock:
    git:
        url: https://github.com/toasterson/hammock.git
        ref: master
dev_dependencies:
  guinness: '>= 0.1.12'
environment:
  sdk: ">=1.4.0 <2.0.0"
